version: '3.8'
services:
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongolocal
      - pg-database

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  pg-database:
    image: postgres:latest
    container_name: pg-database
    hostname: pg-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projects
      PGDATA: /data/postgres
    volumes:
      - dbdata:/data/postgres
    restart: always
    networks:
      - app-network

  mongolocal:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    name: app-network
    driver: bridge
    
volumes:
  mongo-data:
  dbdata:
    name: nest-api
